#!/bin/bash

if [[ -z $SYSROOT ]]; then
	echo "ERROR: You have to set SYSROOT to use cross-emerge-ng!"
	exit 1
fi

# Get host triplet from build platform in /
export CBUILD=$(portageq envvar CHOST)

# Switch to host platform in SYSROOT
export ROOT="${SYSROOT}"
export PORTAGE_CONFIGROOT="${SYSROOT}"

# Get host triplet from host platform in SYSROOT
export CROSS_CHOST=$(portageq envvar CHOST)

if [[ -z $DONT_WRAP_COMPILERS ]]; then
        export CC="__PREFIX__/bin/chost-gcc"
        export CXX="__PREFIX__/bin/chost-g++"
fi

exec emerge "$@"
